### ISSUE TITLE
Caching table throws "Proxy Error"

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/afeefa-backend-ui#266]

**Comment by friedrichweise** [comment]
```
NoMethodError (undefined method `name=' for #<TranslationCache:0x007f99bc656e60>):

app/models/translation_cache.rb:25:in `block in rebuild_db_cache!'
app/models/translation_cache.rb:7:in `each'
app/models/translation_cache.rb:7:in `rebuild_db_cache!'
app/controllers/api/v1/translation_cache_controller.rb:12:in `update'
```

**Comment by friedrichweise** [comment]
Nach 60s wird leider der Timeout des Requests erreicht. Danach werden auch keine weiteren Einträge in die Cache Tabelle geschrieben.
Ich habe die "Auslösung" jetzt über die Rails Konsole ausgeführt:
````
t = Api::V1::TranslationCacheController.new
t.update()
````
Dabei werden 2172 Einträge erstellt. Der Vorgang endet jedoch mit der Meldung:
```
Module::DelegationError: ActionController::Metal#status= delegated to @_response.status=, but @_response is nil: #<Api::V1::TranslationCacheController:0x00000007901d78 @_routes=nil, @_request=nil, @_response=nil, @_config={}, @_db_runtime=86901.57508599976>
from /home/afeefa/rails/afeefa-backend-api-dev/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:149:in `rescue in status='

```

**Comment by friedrichweise** [comment]
Der Vorgang sollte also entkoppelt von dem eigentlich POST Request ausgeführt werden.

**Comment by friedrichweise** [comment]
UI entfernen. Crontab bauen. Täglich ausführen.

**Comment by foobar0112** [comment]
job für komplettes caching funktioniert
- kann vom frontend asynchron getriggert werden
- cronjob wird eingerichtet, der täglich job triggert

**Comment by kakenbok** [comment]
ui noch drinn

**Comment by friedrichweise** [comment]
UI bleibt erstmal drin.

**Comment by kakenbok** [comment]
die cachingtable kann jetzt zusätzlich von lokal per deploy task ausgeführt werden: `cap [dev|production] translation:sync_in`

der button ist weiterhin drin. es wäre zu überlegen, wie sich mehrfache auslösungen verhindern ließen.

**Comment by kakenbok** [comment]
bitte abnehmen
