### ISSUE TITLE
Fehler beim Filtern von Todo's

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-ui#326]
```
{
  "error": "Internal Server Error",
  "exception": "#<ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'orgas.annotation_category_id' in 'where clause': SELECT `annotations`.* FROM `annotations` LEFT JOIN orgas ON orgas.id = annotations.entry_id AND entry_type = 'Orga' LEFT JOIN events ON events.id = annotations.entry_id AND entry_type = 'Event' WHERE (orgas.area = 'Dresden' OR events.area = 'Dresden') AND (orgas.annotation_category_id LIKE '%495%' OR events.annotation_category_id LIKE '%495%') GROUP BY `annotations`.`entry_id`, `annotations`.`entry_type`>",
  "status": 500,
  "traces": {
    "Application Trace": [
      {
        "id": 23,
        "trace": "app/controllers/api/v1/base_controller.rb:76:in `block in render_objects_to_json'"
      },
      {
        "id": 26,
        "trace": "app/controllers/api/v1/base_controller.rb:75:in `render_objects_to_json'"
      },
      {
        "id": 27,
        "trace": "app/controllers/api/v1/base_controller.rb:35:in `index'"
      }
    ],
   }
}
```

**Comment by friedrichweise** [comment]
Sieht mir nach einem temporären Versionierungsproblem aus. Ist nie wieder aufgetreten.
